### ISSUE TITLE
Add gitignore file

### ISSUE THREAD

**Issue by gaurangfgupta** [gaurangfgupta/LearnIdentity#1]
Usually when creating a new repo, we have the option of adding a *.gitignore* by selecting one from provided list of templates. However, I have forked an existing repo **MongoDB.AspNet.Identity** by **InspectorIT** and I wanna use that as a starting point for a new project. I would like to add a (**Visual Studio**) *.gitignore* file to the forked repo but I'm unable to find the templates. I know I can create a new file and simply copy paste from elsewhere but is there a way to add a *.gitgnore* from templates into an existing repo?

@panshul007 Check the branch not master...

**Comment by gaurangfgupta** [comment]
Deleted the branch for now.

**Comment by panshul007** [comment]
u can add the files and folders manually... 
everything that is generated at runtime and some config files like credentials for services should be added to this file.
